export const CONSTANTS = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  CONNECTION_AVAILABLE: 'CONNECTION_AVAILABLE',
  CHANGE_APP_LANGUAGE: 'CHANGE_APP_LANGUAGE',
  CHANGE_CONTENT_LANGUAGE: 'CHANGE_CONTENT_LANGUAGE',
};